import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import SystemArchitectureDiagram from '@/components/reports/SystemArchitectureDiagram';
import TechnicalSpecifications from '@/components/reports/TechnicalSpecifications';
import { motion } from 'framer-motion';
import { ArrowLeft, FileText, Download, Calendar, Activity, AlertTriangle, Target, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { format } from 'date-fns';

export default function Reports() {
  const [isGenerating, setIsGenerating] = useState(false);

  const { data: sites = [] } = useQuery({
    queryKey: ['sites'],
    queryFn: () => base44.entities.Site.list('-created_date', 50)
  });

  const { data: faults = [] } = useQuery({
    queryKey: ['faults'],
    queryFn: () => base44.entities.Fault.list('-created_date', 200)
  });

  const { data: predictions = [] } = useQuery({
    queryKey: ['predictions'],
    queryFn: () => base44.entities.Prediction.list('-created_date', 200)
  });

  const { data: evaluations = [] } = useQuery({
    queryKey: ['evaluations'],
    queryFn: () => base44.entities.EvaluationResult.list('-created_date', 10)
  });

  const { data: maintenance = [] } = useQuery({
    queryKey: ['maintenance'],
    queryFn: () => base44.entities.MaintenanceAction.list('-created_date', 100)
  });

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 2000));

    const latestEval = evaluations[0] || {};
    const activeFaults = faults.filter(f => f.status === 'active').length;
    const criticalPredictions = predictions.filter(p => (p.fault_probability || 0) >= 0.7).length;
    
    const reportContent = `
SCADA Grid Intelligence - System Evaluation Report
Generated: ${format(new Date(), 'MMMM d, yyyy HH:mm')}
================================================================================

EXECUTIVE SUMMARY
-----------------
This report presents the evaluation results for the AI-enabled SCADA fault 
prediction and grid reliability platform. The system demonstrates significant 
improvements in fault detection accuracy and response time.

FLEET OVERVIEW
--------------
• Total Sites Monitored: ${sites.length}
• Active Faults: ${activeFaults}
• High-Risk Predictions (24h): ${criticalPredictions}
• Pending Maintenance Actions: ${maintenance.filter(m => m.status === 'pending').length}

MODEL PERFORMANCE METRICS
-------------------------
• Precision: ${latestEval.precision ? (latestEval.precision * 100).toFixed(1) : 'N/A'}%
• Recall: ${latestEval.recall ? (latestEval.recall * 100).toFixed(1) : 'N/A'}%
• F1 Score: ${latestEval.f1_score ? (latestEval.f1_score * 100).toFixed(1) : 'N/A'}%
• False Alarm Rate: ${latestEval.false_alarm_rate ? (latestEval.false_alarm_rate * 100).toFixed(2) : 'N/A'}%
• Average Early Warning Lead Time: ${latestEval.avg_early_warning_lead_time_min || 'N/A'} minutes

BASELINE VS AI COMPARISON
-------------------------
• Baseline Detection Time: ${latestEval.baseline_detection_time_min || 45} minutes
• AI-Assisted Detection Time: ${latestEval.ai_detection_time_min || 12} minutes
• Fault Isolation Time Reduction: ${latestEval.fault_isolation_time_reduction_pct || 65}%

IMPACT ANALYSIS
---------------
• Downtime Prevented: ${latestEval.downtime_prevented_hr || 24} hours
• Estimated Cost Savings: $${(latestEval.cost_savings_usd || 45000).toLocaleString()}

FAULT DISTRIBUTION (Last 30 Days)
---------------------------------
${Object.entries(
  faults.reduce((acc, f) => {
    const type = f.fault_type || 'unknown';
    acc[type] = (acc[type] || 0) + 1;
    return acc;
  }, {})
).map(([type, count]) => `• ${type.replace(/_/g, ' ')}: ${count}`).join('\n')}

RECOMMENDATIONS
---------------
1. Continue monitoring high-risk sites identified by AI predictions
2. Schedule preventive maintenance for flagged equipment
3. Review and validate AI predictions for continuous model improvement
4. Expand telemetry coverage to improve prediction accuracy

================================================================================
Model Version: ${latestEval.model_version || 'v2.4.1-rf-ensemble'}
Evaluation Period: ${latestEval.evaluation_period_days || 7} days
Report Generated By: SCADA Grid Intelligence Platform
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scada-evaluation-report-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    
    setIsGenerating(false);
  };

  const latestEval = evaluations[0] || {};

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to={createPageUrl('Dashboard')}>
                <Button variant="ghost" size="icon">
                  <ArrowLeft className="w-5 h-5" />
                </Button>
              </Link>
              <div>
                <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
                  Reports & Export
                </h1>
                <p className="text-slate-500 mt-1">
                  Generate and export evaluation reports
                </p>
              </div>
            </div>
            <Button
              onClick={generateReport}
              disabled={isGenerating}
              className="bg-slate-900 hover:bg-slate-800 gap-2"
            >
              <Download className="w-4 h-4" />
              {isGenerating ? 'Generating...' : 'Export Full Report'}
            </Button>
          </div>
        </motion.div>

        {/* Report Preview */}
        <div className="grid lg:grid-cols-3 gap-6 mb-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm h-full">
              <CardHeader className="border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Activity className="w-5 h-5 text-blue-600" />
                  <CardTitle className="text-lg">System Overview</CardTitle>
                </div>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="flex justify-between">
                  <span className="text-slate-500">Sites Monitored</span>
                  <span className="font-semibold">{sites.length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Total Readings</span>
                  <span className="font-semibold">--</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Active Faults</span>
                  <span className="font-semibold">{faults.filter(f => f.status === 'active').length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Model Version</span>
                  <span className="font-semibold text-xs">{latestEval.model_version || 'v2.4.1'}</span>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm h-full">
              <CardHeader className="border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Target className="w-5 h-5 text-violet-600" />
                  <CardTitle className="text-lg">Model Metrics</CardTitle>
                </div>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="flex justify-between">
                  <span className="text-slate-500">Precision</span>
                  <span className="font-semibold">{latestEval.precision ? `${(latestEval.precision * 100).toFixed(1)}%` : '--'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Recall</span>
                  <span className="font-semibold">{latestEval.recall ? `${(latestEval.recall * 100).toFixed(1)}%` : '--'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">F1 Score</span>
                  <span className="font-semibold text-violet-600">{latestEval.f1_score ? `${(latestEval.f1_score * 100).toFixed(1)}%` : '--'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Lead Time</span>
                  <span className="font-semibold">{latestEval.avg_early_warning_lead_time_min || '--'} min</span>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm h-full">
              <CardHeader className="border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-emerald-600" />
                  <CardTitle className="text-lg">Impact Summary</CardTitle>
                </div>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="flex justify-between">
                  <span className="text-slate-500">Detection Improvement</span>
                  <span className="font-semibold text-emerald-600">{latestEval.fault_isolation_time_reduction_pct || 65}%</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Downtime Prevented</span>
                  <span className="font-semibold">{latestEval.downtime_prevented_hr || 24}h</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Cost Savings</span>
                  <span className="font-semibold">${(latestEval.cost_savings_usd || 45000).toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">False Alarm Rate</span>
                  <span className="font-semibold">{latestEval.false_alarm_rate ? `${(latestEval.false_alarm_rate * 100).toFixed(2)}%` : '--'}</span>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Architecture & Specifications */}
        <div className="grid lg:grid-cols-1 gap-6 mb-8">
          <SystemArchitectureDiagram />
        </div>

        <div className="grid lg:grid-cols-1 gap-6 mb-8">
          <TechnicalSpecifications />
        </div>

        {/* Available Reports */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm">
            <CardHeader className="border-b border-slate-100">
              <CardTitle className="text-lg font-semibold text-slate-900">
                Available Export Formats
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid md:grid-cols-3 gap-4">
                <div className="p-4 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors">
                  <div className="flex items-center gap-3 mb-3">
                    <FileText className="w-8 h-8 text-blue-600" />
                    <div>
                      <p className="font-semibold text-slate-900">Full Report</p>
                      <p className="text-sm text-slate-500">Text format</p>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600 mb-3">
                    Complete evaluation report with metrics, analysis, and recommendations.
                  </p>
                  <Button variant="outline" size="sm" onClick={generateReport} className="w-full">
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </div>

                <div className="p-4 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors">
                  <div className="flex items-center gap-3 mb-3">
                    <FileText className="w-8 h-8 text-emerald-600" />
                    <div>
                      <p className="font-semibold text-slate-900">Metrics CSV</p>
                      <p className="text-sm text-slate-500">Spreadsheet format</p>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600 mb-3">
                    Raw metrics data in CSV format for further analysis.
                  </p>
                  <Link to={createPageUrl('Evaluation')}>
                    <Button variant="outline" size="sm" className="w-full">
                      Go to Evaluation
                    </Button>
                  </Link>
                </div>

                <div className="p-4 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors opacity-60">
                  <div className="flex items-center gap-3 mb-3">
                    <FileText className="w-8 h-8 text-red-600" />
                    <div>
                      <p className="font-semibold text-slate-900">PDF Report</p>
                      <p className="text-sm text-slate-500">Print-ready format</p>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600 mb-3">
                    Formatted PDF with charts and visualizations.
                  </p>
                  <Button variant="outline" size="sm" className="w-full" disabled>
                    Coming Soon
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}